AllCops:
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 99

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

  # rubocop-rspec custom configurations

require:
  - rubocop-rspec

RSpec/ExampleLength:
  Max: 10
